Sprint1
Nereee/E3_ML_T1 pull request #1
Opened 2024-02-02 09:27 UTC by Aitzolgy

Badago markak sprint1

2024-02-02 09:35 UTC, Nereee requested changes
main.html bihurtu behar duzue index.html (kontuz nabegazio menu osoan ere aldaketak egin beharko dituzue); eta bere ubikazioa izan beharko du Webgunearen karpeta nagusian

2024-02-02 13:01 UTC, AndoniSalsidua commented
Markak sprint bat login

2024-02-02 13:09 UTC, AndoniSalsidua commented
Badago 1 sprinta eskatutako aldaketekin

2024-02-05 06:33 UTC, Nereee approved these changes

2024-02-05 06:34 UTC, merged